#!/usr/bin/env python3
from conjureup.hooklib.writer import success, fail, error
from conjureup.hooklib import juju
import logging

log = logging.getLogger('conjureup')


log.debug("Running deploy-done for Kubernetes installation.")

agent_states = juju.agent_states()
agent_states_no_es = []

for row in agent_states:
    if 'elasticsearch' not in row[0]:
        agent_states_no_es.append(row)

if any([state == 'error' for _, state, _ in agent_states]):
    error('Error in one of the applications deployment')

if all([state == 'active' for _, state, _ in agent_states_no_es]):
    success('Applications are ready')

fail('Applications not ready yet')
