#!/bin/sh

APPLANG=en_US
APPENC=UTF-8
APPLOC="$APPLANG.$APPENC"

export LC_ALL=$APPLOC
export LANG=$APPLOC
export LANGUAGE=${APPLANG%_*}

# Make sure a lxc certificate is generated within the snap
lxc finger

$SNAP/bin/conjure-up -c $SNAP/etc/conjure-up.conf "$@"
