#!/usr/bin/env python3
from conjureup.hooklib.writer import success, fail, error
from conjureup.hooklib import juju
import logging
from subprocess import run, DEVNULL, PIPE

log = logging.getLogger('conjureup')
status = juju.status()
applications = status['applications']['spark']
zeppelin_ip = applications['units']['spark/0']['public-address']

if zeppelin_ip:
    sh = run('juju expose zeppelin', shell=True,
             stderr=PIPE,
             stdout=DEVNULL)
    if sh.returncode > 0:
        error("Failed to expose Zeppelin UI: {}".format(
            sh.stderr.decode()))
    success("Zeppelin UI is now configured "
            "and can be viewed at http://{}:9090".format(zeppelin_ip))
fail("Unable to determine Zeppelin UI URL")
