.TH "" "" "" "" ""
.SH NAME
.PP
conjure\-setup \- Runtime installer for APT\-Juju packages.
.SH SYNOPSIS
.IP
.nf
\f[C]
$\ conjure\-setup\ \-\-metadata\ metdata.json\ \-\-config\ config.json
\f[]
.fi
.SH DESCRIPTION
.RS
.PP
Package installer runtime for Juju apt packages.
.RE
.SH SEE ALSO
.PP
bundle\-placer(1)
