#!/bin/bash


# Make sure we access our python and juju binaries first
export PATH=$SNAP/bin:$SNAP/usr/bin:/snap/bin:$PATH
export LD_LIBRARY_PATH
LD_LIBRARY_PATH=$SNAP/lib:$SNAP/usr/lib/$(uname -p)-linux-gnu/

exec "$SNAP/bin/juju-wait" "$@"
