name: conjure-up
version: 2.0.0.7
summary: Package runtime for conjure-up spells
description: >
   This package provides conjure-up, an interface to installing spells that
   provide the user with an end to end walkthrough experience for installing and
   using big software.
confinement: strict

apps:
    conjure-up:
        command: conjure-up
    python3:
        command: python3
    shell:
        command: bash

parts:
    conjure:
        plugin: python3
        source: https://github.com/ubuntu/conjure-up.git
        source-type: git
        requirements: parts/conjure/src/requirements.txt
    stage-packages:
        plugin: nil
        stage-packages: [juju, wget]
