#!/usr/bin/env python3
from conjureup.hooklib import juju
from conjureup.hooklib.writer import success, fail, error
import logging

log = logging.getLogger('conjureup')
NUM_AGENTS = 13


log.debug("Running deploy-done for Apache MapReduce installation.")
agent_states = juju.agent_states()

errored_units = [(unit_name, message) for unit_name, state, message
                 in agent_states if state == "error"]
if len(errored_units) > 0:
    errs = "\n".join(["{}: {}".format(n, m) for n, m in errored_units])
    error('Deployment errors:\n{}'.format(errs))

machines = juju.machine_states()
errored_machines = [(name, err) for name, status, err in machines
                    if status == "error"]
if len(errored_machines) > 0:
    errs = "\n".join(["{}: {}".format(n, m) for n, m in errored_machines])
    error("Machine creation errors:\n{}".format(errs))

if len(agent_states) < NUM_AGENTS:
    fail('{} applications are still deploying'.format(
        NUM_AGENTS - len(agent_states)))

active_states = [state == 'active' for _, state, _ in agent_states
                 if state != 'unknown']
if len(active_states) > 0 and all(active_states):
    success('Applications are ready')

fail('Applications not ready yet')
