#!/usr/bin/env python3
from subprocess import run, DEVNULL, PIPE
from conjureup.hooklib import juju
from conjureup.hooklib.writer import success, fail, error


status = juju.status()
applications = status['applications']['ganglia']
ganglia_ip = applications['units']['ganglia/0']['public-address']

if ganglia_ip:
    sh = run('juju expose ganglia', shell=True,
             stderr=PIPE,
             stdout=DEVNULL)
    if sh.returncode > 0:
        error("Failed to expose Ganglia UI: {}".format(sh.stderr.decode()))
    success("Ganglia UI Monitoring is now configured "
            "and can be viewed at http://{}/ganglia".format(ganglia_ip))
fail("Unable to determine Ganglia UI URL")
