#!/usr/bin/env python3
import sys
from subprocess import run, DEVNULL, PIPE
# Conjure-up specific
sys.path.insert(0, '/usr/share/conjure-up/hooklib')
import juju  # noqa
from writer import log, success, fail, error  # noqa


if __name__ == "__main__":
    status = juju.status()
    applications = status['applications']['ganglia']
    ganglia_ip = applications['units']['ganglia/0']['public-address']
    if ganglia_ip:
        sh = run('juju expose ganglia', shell=True,
                 stderr=PIPE,
                 stdout=DEVNULL)
        if sh.returncode > 0:
            error("Failed to expose Ganglia UI: {}".format(sh.stderr.decode()))
        success("Ganglia UI Monitoring is now configured "
                "and can be viewed at http://{}/ganglia".format(ganglia_ip))
    fail("Unable to determine Ganglia UI URL")
