#!/usr/bin/env python3
import sys
from subprocess import run, DEVNULL, PIPE
# Conjure-up specific
sys.path.insert(0, '/usr/share/conjure-up/hooklib')
import juju  # noqa
from writer import log, success, fail, error  # noqa


if __name__ == "__main__":
    status = juju.status()
    applications = status['applications']['kibana']
    ip = applications['units']['kibana/0']['public-address']
    if ip:
        sh = run('juju expose kibana', shell=True,
                 stderr=PIPE,
                 stdout=DEVNULL)
        if sh.returncode > 0:
            error("Failed to expose Kibana UI: {}".format(sh.stderr.decode()))
        success("Kibana is now configured "
                "and can be viewed at http://{}".format(ip))
    fail("Unable to determine Kibana URL")
