#!/bin/sh

APPLANG=en_US
APPENC=UTF-8
APPLOC="$APPLANG.$APPENC"

export LC_ALL=$APPLOC
export LANG=$APPLOC
export LANGUAGE=${APPLANG%_*}

if [ ! -d /var/lib/lxd/ ]; then
    export LXD_DIR=/var/snap/lxd/common/lxd
fi

# Make sure we access our python and juju binaries first
export PATH=$SNAP/bin:$SNAP/usr/bin:/snap/bin:$PATH

exec $SNAP/bin/conjure-down "$@"
