#!/bin/bash

APPLANG=en_US
APPENC=UTF-8
APPLOC="$APPLANG.$APPENC"

export LC_ALL=$APPLOC
export LANG=$APPLOC
export LANGUAGE=${APPLANG%_*}

debian_socket=/var/lib/lxd
snap_lxd_socket=/var/snap/lxd/common/lxd

lxd_binary=$(which lxd)

# Prefer debian installed lxd, if availible
if [ "$lxd_binary" = "/usr/bin/lxd" ]; then
    export LXD_DIR=$debian_socket
elif [ "$lxd_binary" = "/snap/bin/lxd" ]; then
    export LXD_DIR=$snap_lxd_socket
fi

lxc finger > /dev/null 2>&1

exec $SNAP/bin/conjure-up -c $SNAP/etc/conjure-up.conf \
     --spells-dir $SNAP/spells --nosync "$@"
