#!/bin/bash

snap_lxd_socket=/var/snap/lxd/common/lxd
export LXD_DIR=$snap_lxd_socket

# Make sure we access our python and juju binaries first
export PATH=$SNAP/bin:$SNAP/usr/bin:/snap/bin:$PATH

exec $SNAP/bin/juju "$@"
