#!/bin/sh
export LXD_DIR=${SNAP_COMMON}/lxd/
export EDITOR=vim.tiny
export VISUAL=${EDITOR}

export PATH=$SNAP/bin:$SNAP/usr/bin:/snap/bin:$PATH
export LD_LIBRARY_PATH
LD_LIBRARY_PATH=$SNAP/lib:$SNAP/usr/lib/$(uname -p)-linux-gnu/

exec "$SNAP/bin/lxc" "$@"
