#!/bin/sh
export LXD_DIR=${SNAP_COMMON}/lxd/

export PATH=$SNAP/bin:$SNAP/usr/bin:/snap/bin:$PATH
export LD_LIBRARY_PATH
LD_LIBRARY_PATH=$SNAP/usr/lib/$(uname -p)-linux-gnu/

if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

exec "$SNAP/bin/lxd" "$@"
