#!/usr/bin/env python3
from conjureup.hooklib.writer import success, fail, error
from conjureup.hooklib import juju
import logging

log = logging.getLogger('conjureup')

log.debug("Running deploy-done for OpenStack installation.")
agent_states = juju.agent_states()

errored_units = [(unit_name, message) for unit_name, state, message
                 in agent_states if state == "error"]
if len(errored_units) > 0:
    errs = "\n".join(["{}: {}".format(n, m) for n, m in errored_units])
    error('Deployment errors:\n{}'.format(errs))

machines = juju.machine_states()
errored_machines = [(name, err) for name, status, err in machines
                    if status == "error"]
if len(errored_machines) > 0:
    errs = "\n".join(["{}: {}".format(n, m) for n, m in errored_machines])
    error("Machine creation errors:\n{}".format(errs))

if len(agent_states) == 0:
    fail('Applications are still deploying')

if all([state == 'active' for _, state, _ in agent_states]):
    success('Applications are ready')

fail('Applications not ready yet')
