#!/usr/bin/env python3
# -*- mode: python; -*-
#
# version - Parses and prints version from debian/changelog
#
# Copyright 2014 Canonical, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This package is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import re
import os


def print_version():
    """ Prints version string from debian/changelog

    @return: 0 on success 1 on failure
    """
    pattern = 'conjure\s\(([a-zA-Z0-9\.~\-\+]+)\)\s'
    if not os.path.isfile('debian/changelog'):
        print("0.0.0")
        return 0
    with open('debian/changelog', 'r') as f:
        match = re.match(pattern, f.read())
    if match:
        print(match.groups()[0])
        return 0
    return 1

if __name__ == "__main__":
    print_version()
