name: conjure-up
version: 2.1.0
summary: Package runtime for conjure-up spells
description: >
   This package provides conjure-up, an interface to installing spells that
   provide the user with an end to end walkthrough experience for installing and
   using big software.
confinement: classic
grade: stable

apps:
  conjure-up:
    command: wrappers/conjure-up
  conjure-down:
    command: wrappers/conjure-down
    aliases: [conjure-down]
  juju:
    command: bin/juju
    aliases: [juju]
  bridge:
    command: wrappers/bridge.start
    stop-command: wrappers/bridge.stop
    restart-condition: never
    daemon: oneshot

parts:
  conjure-up:
    plugin: python
    source: .
    # source: https://github.com/conjure-up/conjure-up
    # source-type: git
    # source-branch: master
    requirements: requirements.txt
    stage-packages:
      - bsdtar
      - jq
  configs:
    plugin: dump
    source: https://github.com/conjure-up/conjure-up
    source-type: git
    filesets:
      etc/conjure-up.conf: [etc/conjure-up.conf]
  wrappers:
    plugin: dump
    source: snap/
  juju:
    plugin: godeps
    go-importpath: github.com/juju/juju
    source: https://github.com/juju/juju.git
    source-type: git
    source-branch: "2.1"
    prime:
      - bin/juju
      - bin/jujud
