name: conjure-up
version: 2.3-alpha1
version-script: |
  echo "$SNAPCRAFT_PROJECT_VERSION-$(date +%Y%m%d.%H%m)"
summary: Package runtime for conjure-up spells
description: >
   This package provides conjure-up, an interface to installing spells that
   provide the user with an end to end walkthrough experience for installing and
   using big software.
confinement: classic
grade: stable

apps:
  conjure-up:
    command: wrappers/conjure-up
  conjure-down:
    command: wrappers/conjure-down
    aliases: [conjure-down]
  juju:
    command: wrappers/juju
  daemon:
    command: wrappers/daemon.start
    stop-command: wrappers/daemon.stop
    daemon: simple
  lxc:
    command: wrappers/lxc
  lxd:
    command: wrappers/lxd
  redis-server:
    command: wrappers/redis.daemon.start
    daemon: simple
  redis-cli:
    command: wrappers/redis-cli

parts:
  redis:
    plugin: make
    source: https://github.com/antirez/redis.git
    source-tag: 3.2.9
    make-install-var: PREFIX
  conjure-up:
    source: .
    plugin: python
    requirements: requirements.txt
    stage:
      - -README.md
      - -debian
      - -usr/bin/py*
      - -usr/bin/2to3-3.5
      - -usr/share/*python*
      - -usr/lib/python3.5
    stage-packages:
      - bsdtar
      - jq
      - pwgen
    after: [python]
  spells:
    source: https://github.com/conjure-up/spells.git
    source-type: git
    plugin: dump
    organize:
      "*": spells/
    stage:
      - -README.md
    after: [conjure-up]
  wrappers:
    plugin: dump
    source: snap/
    build-packages: [lsb-release]
    after: [conjure-up]
  juju:
    source: https://github.com/juju/juju.git
    source-type: git
    source-branch: "develop"
    source-depth: 1
    plugin: godeps
    go-importpath: github.com/juju/juju
    go-packages:
      - github.com/juju/juju/cmd/juju
      - github.com/juju/juju/cmd/jujud
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bash_completions
      cp -a etc/bash_completion.d/juju* $SNAPCRAFT_PART_INSTALL/bash_completions/.
    build-packages: [lsb-release]
    after: [conjure-up, lxd, go]
  lxd:
    source-tag: lxd-2.14
  go:
    source-tag: go1.8
  python:
    source: https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tar.xz
    plugin: autotools
    configflags: [--prefix=/usr]
    build-packages: [libssl-dev]
  lxc:
    configflags:
    - --disable-selinux
    - --disable-python
    - --disable-lua
    - --disable-tests
    - --disable-examples
    - --disable-doc
    - --disable-api-docs
    - --disable-bash
    - --disable-cgmanager
    - --enable-apparmor
    - --enable-seccomp
    - --enable-capabilities
    - --with-rootfs-path=/var/snap/conjure-up/common/lxc/
    - --libexecdir=/snap/conjure-up/current/libexec/
    organize:
      snap/conjure-up/current/libexec: libexec
    after: [conjure-up]
  lxcfs:
    organize:
      snap/conjure-up/current/lxc: lxc
      snap/conjure-up/current/lxcfs: lxcfs
    configflags:
    - --datarootdir=/snap/conjure-up/current/
    - --localstatedir=/var/snap/conjure-up/common/var/
    after: [conjure-up]
